services:
  greetings-app-dev:
    build: .
    image: peterispp/python-greetings-app:latest
    container_name: greetings-app-dev
    ports:
      - 7001:3000
  greetings-app-stg:
    build: . 
    image: peterispp/python-greetings-app:latest
    container_name: greetings-app-stg
    ports:
      - 7002:3000
  greetings-app-prod:
    build: .
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: peterispp/python-greetings-app:latest
    container_name: greetings-app-prod
    ports:
      - 7003:3000

# To run those (-d to still use the terminal)
# docker compose up -d

# To remove those
# docker compose down
